# Required
version: 2

python:
  version: 3.5
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
