language: python
sudo: false
python:
- '3.6'
- '3.7'
env:
  global:
  - secure: x8IUUQIlfb/RYfdbMdNLy5Q2/WhRWhAmVZqhum1WPZq4DlhQh2o5ntDCavJ3j3iQ3vekYZPksgQicX0Z6NUz8wXH7+gsbgCHvhN4NdDI3sLMpXc95tzHWP5YY1XY9UDryjZjqAiz2FVnmth7Y++gsRnPk2vCzw0xTOpwYDZoA+qLsYWUMZWNZkwQS3HlpeIj1f869+htzgLy+BaeeCUXEdKJF5rxZZpqSOPNIAeribaEKYdGRTtxTu3Sf+pq5rVQ+LM/X/FwzJcGfxrS3yKZErr2tS/DclONGCx8hcY01mTH6+rCb/zYd8NHTU+ZEOI41vICPSWcaoHvajMmLOF8h+6FRYWAYt5yF+GfWVdnuEDMxB1/Czul7+oKI6yh3Uv0R5/Nlhu8gpZ2Qwr9zk9OyZd9X1cYtRTEpPiqH2mc4aylclR1/MD/nLs1bHB+K591duyyWPtUQE7BFT0gksLLT9S/mt2p8pPu7CF6ZTAViLD4yUArmjBF/acP/QfThaXuHWqGUxO2oRvcD/YYPwyGWw/I2qmvVSAAZwNkaMahN6SAb5vgu3yOMrsQt6xDN+dcoqNQNu1tno4naFUnYzxW0ozR4mCTycAvbh9BknxuE5gAj/mAn4ZP4et6nwXyYbqJbeAFdhlwxL8ttiqgwZLdXD9oxBYlptPORzQCrpS3U74=
  - secure: OwuTOD492otctyIHIvb8KPYDEs48yDqcdiP7vSxnhqFvYWFg4ug7D1kx5SMxhWR/5ciykMT4M2EE9U+tmRlmIAd8VqIbBZui7Gp8MVClJ7svuCgqnrrSMApIzBdgyis2WIlWCK4mdymC50PcaDPNJLwZ5YpbdvVya6SFSNIBnNxrqK5gIlQ+G7xK7j4vPZIf2ayNIrI+gJG5kkViFRrSU3JboWd4JLEp58sk7xPZsAGhk+5T2SnlZtZTGGfUmOiSSwpVE+uCyHnGR2PhnAXAZ0ogT+iLFC4jPmYa69c+xHtY1rXWeVQ0w1GUOa3/JkiDyeO0O0NPXCI0tldnV1MLeZ+UOvjsk0MYTSIt8EIWfMHkEIkuRR7lA7kvbS+PNZe2ZxAjk9CHpR8t21XJqUqq7/6ZrqrX9DSsrkUYbfQiTyLOzf9/VhO5djHoU2QQa6l04FWhtc+SG+wXuZAnMLfDGo8Nzx7kS3HQsgkH+8NhxT1qIBvgCRqGEfwIq5R8g+Y2z83+zpsLYiZ7HN6T9AoMBzsVFdNIu06289x+PdfigsEglGx8ErdBQRdPEFYvohRwWTujrZqiTFGb3/1Z4SLielGdWKjt7UQJeaEGH3pD9sP9ZAtslHHnAO38GBt2hUe4dlAyPGh38REo3xlL01U8moiFyy69PryMoyXi+UCqjOE=
  - secure: wq6H6+aa2qBhVRMZRqVtsuudVV/pZlONoVgVcJI3BRKhESw42lqHgUt/ptHxX1t26ZAjKrMmAEEGIok8qNfnTPMMurm+pa8pf/vqXiFLhb82DBvUUm38WdIvBZQ4WKrX4FeSm6aZVJJeCBsNsReQ/X4T7S2aFBgztdtkIU1JHpUt4oYhnpVIPOHsyUa8gp+wM4TqnorCdqvhlu5OdlYdAW34GnscRP89UJS9JH5M7ZyM7wV6/s+Uyav7fgV2bRjDC57tSd/OjbyMmMEHgKvvygL7qiTQm/YQFkotfVFTowxdCwzsGJwb7Qf87SShrp2IFXKsyYH3LgOUcPg3GYPBTTaVT1PCezAm63Q6WF/S2mc+VeZgDvYO6gaGNpp6v8VLGi5e36NWBX3xPAzqdZS/lxehC3BD2vE762km7arCQLm7HlFyw+QA/0m/tdOu+roarUy+2xFTy7+NH4eqP8RI7CwpknNJsapImGqAOnSh6ZWMWoIKZPIuSQdULgvNfAooSNdHUnOSx/EmCZ3e0GSLlmtVZG624k13uvvKorLBH5d0LC4wf/yeoKFdnQThgtzvvIsfs8k/TI+52+TNdUEV65nCr2834TkYUX2lG2qGU1/9IXNWT2JyZg4g+3t2nwcZbN6YYdt39PUeSnQ4kMiNHKZiRB4USyTcWxzbp6P/PB0=
  - secure: z6WQVmKFTWf7in9J8764ic6gs5QyLctGYIDzstjSBXYrLTUfJjUwB7OAup1fAFXYUxtzkn6vjn3CIuy+5Nq7jL25Bwen4SJCPZtk9w/8acXUNDNlIFIak7T/jelOO11gHxHI6j2H+wj1BGxz1XZEkx8eeUN6389yvWgHQH01sbrQ7gXRgfmK+1pvUK9Li+4Mn9gBbOoqDxz2w8Wuazkk/FcmlYRYet4z8/y4FHwyc+Sa69utVJQAhDwJzngtb5WRdlWlrcFfyWhQ0eZ/shKxBcjekU5ZeLCh0av4ttB2IXVvLHzsr6vuCssRJqC7LHqiWEpXacWSf0ZOpMlAzwT+fPH5xXSl1kdc8vkpz8gYC5YDDMxkTrUoRv8vCYi/KWmYXNzdiAQn53aX741fcj5FV8v0ybmdPPQLfeQPDhCeHLlroWZsI5cgygxotIfeQzOY3MXSi+YqtZjmuHjAC1aINn9sLwYtCbV1ZVn3TxPaMyWjPlBuOaYoU6GkC+HxAcUy9QMVxBBzbVbOnaPri8NTXxHE58cIz+6GZVou4UDpEjjpi3Z8hieXu5cR0KKFVPofIQlgLaFZ9YgtAuXW6RP2k7ONYyCbW7bz39nnY6outFe96yR/HB4UKqBwc8dIUPfgzyoEyE1obnuNcsNf6UZf+B5ALM03ejQCx9KJuFPrZSw=
jobs:
  include:
  - stage: tests
    before_install:
    - pip install poetry
    install:
    - echo "Installing through poetry then running tests"
    - poetry install
    - pip install coveralls
    script:
    - flake8 dcicutils
    - travis_wait coverage run --source=dcicutils -m pytest -vv test
    - coveralls
    deploy:
      provider: script
      script: poetry publish --build --username=$PYPI_USER --password=$PYPI_PASSWORD
      on:
        tags: true
    after_success:
    - echo "Finished running tests"
    - |
      if [[ $TRAVIS_BRANCH == 'master' ]]; then
        echo 'Triggering docs build'
        curl -X POST -d "branches=master" -d "token=$DOCS_TOKEN" https://readthedocs.org/api/v2/webhook/dcic-utils/99616/
      fi
