language: python
sudo: false
cache:
  pip: true
python:
- '3.5'
deploy:
  provider: pypi
  user:
    secure: Jpkqo70FGa0K1+VGPIvgAisNa1FB/Hd4rcwgxJtYUQc3wby+nyxuIrzsu7NOsYkDJ8vxaE/FbKND1ZFW18vbD9kY6S3/oMSCE5f4fAEhpPEMlOGW5jLI00427PdhbYxk1X2NkhMpU5mEYFFoEf4+GsfoO6zKhhH/xVHjirrcKSJoThQpbYymvJ6uQAuNddSSxqDIcHJGDEfFPUqydOlqgi4oizCagl8N+gIJqpDQ6VQopN8tdM/4YavMaOF7yeU/XEYBQLQgldcjwIeP/X0hy3bLpphgI2MoZ2Y8mJjWF3sC6stKhIjXrUdcjodpzPTJSVuaio1FajTn0h6E1COa+lmckWtzdkGIgSmA6gwKh44nFQcDSV/8fD/or4xjc210V1tG12+MugOuI5q4NFmjbjNEsKw7KIoDqPGRdfE/HZOr30oLWTgaEqdTtG0SzdFfQPq84P80UGlcv68CgnrXtQGwXR08/H4NsuDhnjBKFXZq1afC7Tqw7JtlJyXQmJnmKElrXNaugJe4ru4RY+FlGCt44QZe/sozzFutzqWUfNUrDP2AP+saF7CiH6kD+tcPDioD18dJx0Y0E726Hu7O4wGZk6gl1AYV0LluXulDBO1x8/5vJtzolvC4AsXYWAhk+uUP4j1pO0Pmi+ahuEyyYdUQScMr+gNe0aa/JpzV2L0=
  password:
    secure: dP62awneMbu7jlpFmkQpwGqDxmqlOJorbWjh51BLOuPDc/LHOlI50vdLCwNLwfQFedKoP5LZIfWYBoy8wbXLhXpqZkgwwPvBesaUPuRONdxLqXCqM21d/1nmgIEIdwgFkcIKTRwTPK5LKygXg5iAstkrq+kcdv0Hwake4QE7ZtJEo2kTKPF8jkzHteeBfSB1n6GrQ6iQnkzMg6RiqjB3t0sdNRX/sKZqM5CdYzA523tDjrPTGTWyhVS++/TeNW5PZajZyVr2HKH5+OYp5Ik/8w0Q6EXM51ZuFrqTnv67kTCSIfXai6tpCauI3x3EiUVhkyznIXz2uC5i518GWQWwbuf+k4IKmhXtUe6uA+rVaCkdBOjBN6CyLGJwKaefCJw/RMgWKnqqrHr+6hfwKJctQVxDQcXpvP3+O+LkqBY3D1CYtSjAiini3ooKa2UQGGBhCe8HcPXsMwzPzefdv36RdGASg4X27qOTCKm4F+Jzo9LWF5K3AmYDyGUOXlpfSK1gug6DBrp3VsE3rNX3z8PRj5+LZhDXKg/K99FzM3lsoYypP/V5btoZ3rbUvklRueotSjIO2mohzX4aJ7cZt8hMuoABaXdyIEggWccPYCkOnBnJ0yiXp/PpiRdXeVF2G7eo5fRM/TWPAkvNUJpFvQBRCtvW3xmirY+7Rf79S8FntHM=
  on:
    tags: true
  distributions: sdist bdist_wheel
jobs:
  include:
  - stage: unit tests
    install:
    - pip install -U -r requirements-dev.txt
    - pip install -U -r requirements.txt
    - pip install coveralls
    - pip install codacy-coverage
    - pip install tox
    script:
    - travis_wait invoke test
    - python-codacy-coverage -r coverage.xml
    - coveralls
    after_success:
    - echo "Finished running tests on repo"
  - stage: install tests
    install:
    - echo "Installing package and running tests on the installed package"
    - python setup.py build
    - python setup.py install
    script:
    - travis_wait python setup.py test
    after_success:
    - echo "Finished running package tests"
env:
  global:
  - secure: x8IUUQIlfb/RYfdbMdNLy5Q2/WhRWhAmVZqhum1WPZq4DlhQh2o5ntDCavJ3j3iQ3vekYZPksgQicX0Z6NUz8wXH7+gsbgCHvhN4NdDI3sLMpXc95tzHWP5YY1XY9UDryjZjqAiz2FVnmth7Y++gsRnPk2vCzw0xTOpwYDZoA+qLsYWUMZWNZkwQS3HlpeIj1f869+htzgLy+BaeeCUXEdKJF5rxZZpqSOPNIAeribaEKYdGRTtxTu3Sf+pq5rVQ+LM/X/FwzJcGfxrS3yKZErr2tS/DclONGCx8hcY01mTH6+rCb/zYd8NHTU+ZEOI41vICPSWcaoHvajMmLOF8h+6FRYWAYt5yF+GfWVdnuEDMxB1/Czul7+oKI6yh3Uv0R5/Nlhu8gpZ2Qwr9zk9OyZd9X1cYtRTEpPiqH2mc4aylclR1/MD/nLs1bHB+K591duyyWPtUQE7BFT0gksLLT9S/mt2p8pPu7CF6ZTAViLD4yUArmjBF/acP/QfThaXuHWqGUxO2oRvcD/YYPwyGWw/I2qmvVSAAZwNkaMahN6SAb5vgu3yOMrsQt6xDN+dcoqNQNu1tno4naFUnYzxW0ozR4mCTycAvbh9BknxuE5gAj/mAn4ZP4et6nwXyYbqJbeAFdhlwxL8ttiqgwZLdXD9oxBYlptPORzQCrpS3U74=
  - secure: OwuTOD492otctyIHIvb8KPYDEs48yDqcdiP7vSxnhqFvYWFg4ug7D1kx5SMxhWR/5ciykMT4M2EE9U+tmRlmIAd8VqIbBZui7Gp8MVClJ7svuCgqnrrSMApIzBdgyis2WIlWCK4mdymC50PcaDPNJLwZ5YpbdvVya6SFSNIBnNxrqK5gIlQ+G7xK7j4vPZIf2ayNIrI+gJG5kkViFRrSU3JboWd4JLEp58sk7xPZsAGhk+5T2SnlZtZTGGfUmOiSSwpVE+uCyHnGR2PhnAXAZ0ogT+iLFC4jPmYa69c+xHtY1rXWeVQ0w1GUOa3/JkiDyeO0O0NPXCI0tldnV1MLeZ+UOvjsk0MYTSIt8EIWfMHkEIkuRR7lA7kvbS+PNZe2ZxAjk9CHpR8t21XJqUqq7/6ZrqrX9DSsrkUYbfQiTyLOzf9/VhO5djHoU2QQa6l04FWhtc+SG+wXuZAnMLfDGo8Nzx7kS3HQsgkH+8NhxT1qIBvgCRqGEfwIq5R8g+Y2z83+zpsLYiZ7HN6T9AoMBzsVFdNIu06289x+PdfigsEglGx8ErdBQRdPEFYvohRwWTujrZqiTFGb3/1Z4SLielGdWKjt7UQJeaEGH3pD9sP9ZAtslHHnAO38GBt2hUe4dlAyPGh38REo3xlL01U8moiFyy69PryMoyXi+UCqjOE=
  - secure: wq6H6+aa2qBhVRMZRqVtsuudVV/pZlONoVgVcJI3BRKhESw42lqHgUt/ptHxX1t26ZAjKrMmAEEGIok8qNfnTPMMurm+pa8pf/vqXiFLhb82DBvUUm38WdIvBZQ4WKrX4FeSm6aZVJJeCBsNsReQ/X4T7S2aFBgztdtkIU1JHpUt4oYhnpVIPOHsyUa8gp+wM4TqnorCdqvhlu5OdlYdAW34GnscRP89UJS9JH5M7ZyM7wV6/s+Uyav7fgV2bRjDC57tSd/OjbyMmMEHgKvvygL7qiTQm/YQFkotfVFTowxdCwzsGJwb7Qf87SShrp2IFXKsyYH3LgOUcPg3GYPBTTaVT1PCezAm63Q6WF/S2mc+VeZgDvYO6gaGNpp6v8VLGi5e36NWBX3xPAzqdZS/lxehC3BD2vE762km7arCQLm7HlFyw+QA/0m/tdOu+roarUy+2xFTy7+NH4eqP8RI7CwpknNJsapImGqAOnSh6ZWMWoIKZPIuSQdULgvNfAooSNdHUnOSx/EmCZ3e0GSLlmtVZG624k13uvvKorLBH5d0LC4wf/yeoKFdnQThgtzvvIsfs8k/TI+52+TNdUEV65nCr2834TkYUX2lG2qGU1/9IXNWT2JyZg4g+3t2nwcZbN6YYdt39PUeSnQ4kMiNHKZiRB4USyTcWxzbp6P/PB0=
  - secure: z6WQVmKFTWf7in9J8764ic6gs5QyLctGYIDzstjSBXYrLTUfJjUwB7OAup1fAFXYUxtzkn6vjn3CIuy+5Nq7jL25Bwen4SJCPZtk9w/8acXUNDNlIFIak7T/jelOO11gHxHI6j2H+wj1BGxz1XZEkx8eeUN6389yvWgHQH01sbrQ7gXRgfmK+1pvUK9Li+4Mn9gBbOoqDxz2w8Wuazkk/FcmlYRYet4z8/y4FHwyc+Sa69utVJQAhDwJzngtb5WRdlWlrcFfyWhQ0eZ/shKxBcjekU5ZeLCh0av4ttB2IXVvLHzsr6vuCssRJqC7LHqiWEpXacWSf0ZOpMlAzwT+fPH5xXSl1kdc8vkpz8gYC5YDDMxkTrUoRv8vCYi/KWmYXNzdiAQn53aX741fcj5FV8v0ybmdPPQLfeQPDhCeHLlroWZsI5cgygxotIfeQzOY3MXSi+YqtZjmuHjAC1aINn9sLwYtCbV1ZVn3TxPaMyWjPlBuOaYoU6GkC+HxAcUy9QMVxBBzbVbOnaPri8NTXxHE58cIz+6GZVou4UDpEjjpi3Z8hieXu5cR0KKFVPofIQlgLaFZ9YgtAuXW6RP2k7ONYyCbW7bz39nnY6outFe96yR/HB4UKqBwc8dIUPfgzyoEyE1obnuNcsNf6UZf+B5ALM03ejQCx9KJuFPrZSw=
