# dcicutils GA Workflow

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test dcicutils with Python ${{ matrix.python_version }}
    
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python_version: [3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Deps
        run: |
          pip install poetry

      - name: QA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ENCRYPT_KEY: ${{ secrets.S3_ENCRYPT_KEY }}
          GLOBAL_ENV_BUCKET: foursight-envs
        run: |
          poetry install
          make test-for-ga

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.python_version == '3.9' }}
        run: |
          poetry run coveralls --service=github
